
services:
  ceibo:
    image: dtechdhgr/ceibo:latest
    container_name: ceibo
    restart: unless-stopped
    env_file: .env
    ports:
      - 5000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ceibo.rule=Host(`ceibo.midominio.com`)"
      - "traefik.http.routers.ceibo.entrypoints=websecure"
      - "traefik.http.routers.ceibo.tls.certresolver=myresolver"
networks:
  proxy:
    external: true

